/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';


export namespace Components {

  interface SwcStackoverflowCard {
    /**
    * (required) The user id to display
    */
    'userId': string;
  }
  interface SwcStackoverflowCardAttributes extends StencilHTMLAttributes {
    /**
    * (required) The user id to display
    */
    'userId'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SwcStackoverflowCard': Components.SwcStackoverflowCard;
  }

  interface StencilIntrinsicElements {
    'swc-stackoverflow-card': Components.SwcStackoverflowCardAttributes;
  }


  interface HTMLSwcStackoverflowCardElement extends Components.SwcStackoverflowCard, HTMLStencilElement {}
  var HTMLSwcStackoverflowCardElement: {
    prototype: HTMLSwcStackoverflowCardElement;
    new (): HTMLSwcStackoverflowCardElement;
  };

  interface HTMLElementTagNameMap {
    'swc-stackoverflow-card': HTMLSwcStackoverflowCardElement
  }

  interface ElementTagNameMap {
    'swc-stackoverflow-card': HTMLSwcStackoverflowCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
